[package]
name = "krun-init-blob"
version = "0.1.0-2.0.0-dev"
edition = "2024"
description = "Default init binary blob for libkrun guests"
license = "Apache-2.0"
repository = "https://github.com/containers/libkrun"
build = "build.rs"

[features]
amd-sev = []
tdx = []
timesync = []
ffi = []

[dependencies]
ffier = { git = "https://github.com/mtjhrc/ffier.git", rev = "289162e" }
libloading = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"

[lib]
name = "krun_init"
path = "src/lib.rs"
crate-type = ["lib", "cdylib"]
