[package]
name = "krun-init-blob"
version = "0.1.0-2.0.0-dev"
edition = "2024"
description = "Default init binary blob for libkrun guests"
license = "Apache-2.0"
repository = "https://github.com/containers/libkrun"
build = "build.rs"

[features]
amd-sev = []
tdx = []
timesync = []
ffi = ["ffier-gen-c-header", "ffier-gen-rust-client", "ffier-schema"]

[dependencies]
ffier = { git = "file:///home/mhrica/Dev2/ffier/ffier.git", rev = "aaafc8a8ad351ec1b05eae7c5f929e275273bc4d" }
ffier-gen-c-header = { git = "file:///home/mhrica/Dev2/ffier/ffier.git", rev = "aaafc8a8ad351ec1b05eae7c5f929e275273bc4d", optional = true }
ffier-gen-rust-client = { git = "file:///home/mhrica/Dev2/ffier/ffier.git", rev = "aaafc8a8ad351ec1b05eae7c5f929e275273bc4d", optional = true }
ffier-schema = { git = "file:///home/mhrica/Dev2/ffier/ffier.git", rev = "aaafc8a8ad351ec1b05eae7c5f929e275273bc4d", optional = true }
krun-via-cdylib-weak = { path = "../../src/libkrun-via-cdylib-weak" }
libloading = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"

[lib]
name = "krun_init"
path = "src/lib.rs"
crate-type = ["lib", "cdylib"]

[[bin]]
name = "krun-init-blob-gen"
path = "src/gen.rs"
required-features = ["ffi"]
