/* @generated by: make gen-libkrun-bindings — do not edit manually. */
#ifndef LIBKRUN_H
#define LIBKRUN_H

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>

typedef void* KrunError;
typedef void* KrunMmioDeviceManager;
typedef void* KrunFsDevice;
typedef void* KrunConsoleDevice;
typedef void* KrunConsoleBuilder;
typedef void* KrunFsOverlay;
typedef void* KrunPayload;
typedef void* KrunVmmBuilder;
typedef void* KrunVmm;
typedef void* KrunVmmHandle;
typedef void* KrunBalloonDevice;
typedef void* KrunRngDevice;
typedef void* KrunVsockDevice;
typedef void* KrunAttachDevice; /* KrunFsDevice | KrunConsoleDevice | KrunBalloonDevice | KrunRngDevice | KrunVsockDevice */
typedef void* KrunError; /* KrunError | KrunVtableError */
typedef void* KrunPushStr; /* KrunVtablePushStr */

#ifndef KRUN_PRIMITIVES_DEFINED
#define KRUN_PRIMITIVES_DEFINED

typedef void* KrunObject; /* KrunError | KrunMmioDeviceManager | KrunFsDevice | KrunConsoleDevice | KrunConsoleBuilder | KrunFsOverlay | KrunPayload | KrunVmmBuilder | KrunVmm | KrunVmmHandle | KrunBalloonDevice | KrunRngDevice | KrunVsockDevice */

typedef uint64_t KrunResult;
#define KRUN_RESULT_SUCCESS 0

/* Caller must ensure data is valid UTF-8 */
typedef struct {
    const char* data;
    size_t len;
} KrunStr;

typedef struct {
    const uint8_t* data;
    size_t len;
} KrunBytes;

#define KRUN_STR(s) ((KrunStr){ .data = (s), .len = (s) ? strlen(s) : 0 })
#if defined(__GNUC__)
#define KRUN_BYTES(arr) ({ \
    _Static_assert( \
        !__builtin_types_compatible_p(typeof(arr), typeof(&(arr)[0])), \
        "KRUN_BYTES() requires an array, not a pointer"); \
    ((KrunBytes){ .data = (const uint8_t*)(arr), .len = sizeof(arr) }); \
})
#else
#define KRUN_BYTES(arr) \
    ((KrunBytes){ .data = (const uint8_t*)(arr), .len = sizeof(arr) })
#endif

/**
 * Stack-allocated temporary handle for passing vtable-based objects.
 * Only valid for the duration of the call — the callee borrows, not owns.
 */
typedef struct {
    uint32_t type_tag;
    uint32_t metadata;
    const void *vtable_ptr;
    const void *user_data;
    uint16_t vtable_size;
} KrunVtableHandle;

#define KRUN_VTABLE_HANDLE(tag, vtable, self_data) \
    ((KrunVtableHandle){ .type_tag = (tag), .metadata = 0, \
      .vtable_ptr = &(vtable), .user_data = (self_data), \
      .vtable_size = sizeof(vtable) })

/**
 * Opaque 16-byte handle entry in an object array.
 * Do not access fields directly — pass &entry to typed methods.
 * Do NOT pass individual entries to destroy.
 */
typedef struct {
    uint32_t _tag;
    uint32_t _meta;
    const void* _ptr;
} KrunObjectArrayEntry;

/**
 * Contiguous array of borrowed handles.
 * Returned by methods that produce slices of handles.
 * Individual elements must NOT be passed to destroy —
 * call free_object_array() to free the entire array.
 */
typedef struct {
    const KrunObjectArrayEntry* items;
    size_t len;
} KrunObjectArray;

#define KRUN_OBJECT_ARRAY_GET(arr, i) \
    (assert((size_t)(i) < (arr).len), (KrunObject)(void*)&(arr).items[(i)])

#endif /* KRUN_PRIMITIVES_DEFINED */

/* Free an owned string returned by the library */
void krun_str_free(KrunStr s);
typedef void (*krun_str_free_fn)(KrunStr s);

/* Free an object array returned by the library */
void krun_free_object_array(KrunObjectArray a);
typedef void (*krun_free_object_array_fn)(KrunObjectArray a);


/* KernelFormat ------------------------------------------------------ */

#define KRUN_KERNEL_FORMAT_ELF 0
#define KRUN_KERNEL_FORMAT_RAW 1

/* LogLevel ---------------------------------------------------------- */

#define KRUN_LOG_LEVEL_OFF 0
#define KRUN_LOG_LEVEL_ERROR 1
#define KRUN_LOG_LEVEL_WARN 2
#define KRUN_LOG_LEVEL_INFO 3
#define KRUN_LOG_LEVEL_DEBUG 4
#define KRUN_LOG_LEVEL_TRACE 5

/* LogStyle ---------------------------------------------------------- */

#define KRUN_LOG_STYLE_AUTO 0
#define KRUN_LOG_STYLE_ALWAYS 1
#define KRUN_LOG_STYLE_NEVER 2

/* LogOptions -------------------------------------------------------- */

#define KRUN_LOG_OPTIONS_NO_ENV 1

/* Error ------------------------------------------------------------- */

#define KRUN_ERROR__INVALID_PARAM ((uint64_t)16777229 << 32 | 1)
#define KRUN_ERROR__DUPLICATE_DEVICE ((uint64_t)16777229 << 32 | 2)
#define KRUN_ERROR__DEVICE_LIMIT_EXCEEDED ((uint64_t)16777229 << 32 | 3)
#define KRUN_ERROR__MISSING_CONFIG ((uint64_t)16777229 << 32 | 4)
#define KRUN_ERROR__CONFLICTING_CONFIG ((uint64_t)16777229 << 32 | 5)
#define KRUN_ERROR__OUT_OF_RANGE ((uint64_t)16777229 << 32 | 6)
#define KRUN_ERROR__FILE_NOT_FOUND ((uint64_t)16777229 << 32 | 7)
#define KRUN_ERROR__PERMISSION_DENIED ((uint64_t)16777229 << 32 | 8)
#define KRUN_ERROR__RESOURCE_ALLOC ((uint64_t)16777229 << 32 | 9)
#define KRUN_ERROR__BAD_FD ((uint64_t)16777229 << 32 | 10)
#define KRUN_ERROR__BACKEND_UNAVAILABLE ((uint64_t)16777229 << 32 | 11)
#define KRUN_ERROR__FEATURE_DISABLED ((uint64_t)16777229 << 32 | 12)
#define KRUN_ERROR__DISK_FORMAT_ERROR ((uint64_t)16777229 << 32 | 13)
#define KRUN_ERROR__ALREADY_STARTED ((uint64_t)16777229 << 32 | 14)
#define KRUN_ERROR__VALIDATION_FAILED ((uint64_t)16777229 << 32 | 15)
#define KRUN_ERROR__HYPERVISOR_ERROR ((uint64_t)16777229 << 32 | 16)
#define KRUN_ERROR__BOOT_ERROR ((uint64_t)16777229 << 32 | 17)
#define KRUN_ERROR__INTERNAL ((uint64_t)16777229 << 32 | 18)

/* MmioDeviceManager ------------------------------------------------- */

/** Create an empty device manager. */
KrunMmioDeviceManager krun_mmio_device_manager_new();
typedef KrunMmioDeviceManager (*krun_mmio_device_manager_new_fn)();
/**
 * Add a device to this manager.
 *
 * Devices are attached in the order they are added. The device must
 * implement [`AttachDevice`] — all built-in device types
 * (`FsDevice`, `ConsoleDevice`, etc.) implement this trait.
 */
void krun_mmio_device_manager_add(KrunMmioDeviceManager handle, KrunAttachDevice device);
typedef void (*krun_mmio_device_manager_add_fn)(KrunMmioDeviceManager handle, KrunAttachDevice device);
void krun_mmio_device_manager_destroy(KrunMmioDeviceManager handle);
typedef void (*krun_mmio_device_manager_destroy_fn)(KrunMmioDeviceManager handle);

/* FsDevice ---------------------------------------------------------- */

/**
 * Create a new virtiofs device sharing a host directory.
 *
 * # Arguments
 *
 * - `tag`: the filesystem tag visible to the guest (e.g. `"/dev/root"`).
 * - `host_path`: the host directory to share.
 */
KrunFsDevice krun_fs_device_new(KrunStr tag, KrunStr host_path, KrunError* err_out);
typedef KrunFsDevice (*krun_fs_device_new_fn)(KrunStr tag, KrunStr host_path, KrunError* err_out);
/** Create a read-only virtiofs device sharing a host directory. */
KrunFsDevice krun_fs_device_new_read_only(KrunStr tag, KrunStr host_path, KrunError* err_out);
typedef KrunFsDevice (*krun_fs_device_new_read_only_fn)(KrunStr tag, KrunStr host_path, KrunError* err_out);
/**
 * Create a virtiofs device with no host directory (NullFs).
 *
 * The guest sees an empty filesystem. Use [`FsOverlay`] to build
 * virtual entries and [`set_overlay`](Self::set_overlay) to attach
 * them.
 */
KrunFsDevice krun_fs_device_new_null(KrunStr tag, KrunError* err_out);
typedef KrunFsDevice (*krun_fs_device_new_null_fn)(KrunStr tag, KrunError* err_out);
/**
 * Set a pre-built [`FsOverlay`] on this device.
 *
 * The overlay entries are resolved (applied to the underlying
 * virtiofs device) during [`attach`](AttachDevice::attach).
 */
void krun_fs_device_set_overlay(KrunFsDevice handle, KrunFsOverlay overlay);
typedef void (*krun_fs_device_set_overlay_fn)(KrunFsDevice handle, KrunFsOverlay overlay);
/**
 * Set the size of the DAX (direct access) shared memory window.
 *
 * When set, the guest can memory-map files from the shared filesystem
 * directly into its address space, avoiding data copies. If not set,
 * no DAX window is allocated.
 */
void krun_fs_device_set_dax_window_size(KrunFsDevice handle, uint64_t bytes);
typedef void (*krun_fs_device_set_dax_window_size_fn)(KrunFsDevice handle, uint64_t bytes);
void krun_fs_device_destroy(KrunFsDevice handle);
typedef void (*krun_fs_device_destroy_fn)(KrunFsDevice handle);

/* ConsoleDevice ----------------------------------------------------- */

/** Create a new console builder. */
KrunConsoleBuilder krun_console_device_builder();
typedef KrunConsoleBuilder (*krun_console_device_builder_fn)();
void krun_console_device_destroy(KrunConsoleDevice handle);
typedef void (*krun_console_device_destroy_fn)(KrunConsoleDevice handle);

/* ConsoleBuilder ---------------------------------------------------- */

/**
 * Add a TTY-backed port to the console.
 *
 * If the fd refers to a real terminal, raw mode will be enabled on it
 * when the VM starts, and restored on shutdown.
 *
 * # Arguments
 *
 * - `name`: the port name visible to the guest (e.g. `"tty0"`).
 * - `tty_fd`: borrowed fd for the host TTY; duplicated internally, caller retains ownership.
 *
 * # Returns
 *
 * The zero-based port index.
 */
KrunResult krun_console_builder_add_tty_port(KrunConsoleBuilder handle, KrunStr name, int tty_fd, uint32_t* result, KrunError* err_out);
typedef KrunResult (*krun_console_builder_add_tty_port_fn)(KrunConsoleBuilder handle, KrunStr name, int tty_fd, uint32_t* result, KrunError* err_out);
/**
 * Add a port with separate input and output fds (no terminal properties).
 * Pass `None` to disable that direction.
 */
KrunResult krun_console_builder_add_inout_port(KrunConsoleBuilder handle, KrunStr name, int input_fd, int output_fd, uint32_t* result, KrunError* err_out);
typedef KrunResult (*krun_console_builder_add_inout_port_fn)(KrunConsoleBuilder handle, KrunStr name, int input_fd, int output_fd, uint32_t* result, KrunError* err_out);
/** Build the console device. At least one port must have been added. */
KrunConsoleDevice krun_console_builder_build(KrunConsoleBuilder handle, KrunError* err_out);
typedef KrunConsoleDevice (*krun_console_builder_build_fn)(KrunConsoleBuilder handle, KrunError* err_out);
/**
 * Set up the default console: port 0 (hvc0) plus named redirect ports.
 *
 * Replicates the v1 `krun_add_virtio_console_default` behaviour:
 *
 * - If any fd is a terminal, port 0 becomes a full TTY console
 *   (raw mode enabled), and that fd is NOT added as a redirect port.
 * - Otherwise, port 0 gets log output and named redirect ports
 *   (`krun-stdin`, `krun-stdout`, `krun-stderr`) are added.
 *
 * Pass `None` to skip a stream.
 */
KrunResult krun_console_builder_add_default_console(KrunConsoleBuilder handle, int stdin, int stdout, int stderr, KrunError* err_out);
typedef KrunResult (*krun_console_builder_add_default_console_fn)(KrunConsoleBuilder handle, int stdin, int stdout, int stderr, KrunError* err_out);
void krun_console_builder_destroy(KrunConsoleBuilder handle);
typedef void (*krun_console_builder_destroy_fn)(KrunConsoleBuilder handle);

/* FsOverlay --------------------------------------------------------- */

/** Create a new empty overlay. */
KrunFsOverlay krun_fs_overlay_new();
typedef KrunFsOverlay (*krun_fs_overlay_new_fn)();
/**
 * Add a virtual directory entry.
 *
 * `path` may contain `/` separators for nested entries (e.g. `"etc/nested"`).
 * Intermediate directories must already exist in the overlay.
 */
void krun_fs_overlay_add_dir(KrunFsOverlay handle, KrunStr path, uint32_t mode);
typedef void (*krun_fs_overlay_add_dir_fn)(KrunFsOverlay handle, KrunStr path, uint32_t mode);
/**
 * Add a virtual file entry.
 *
 * `path` may contain `/` separators for nested entries (e.g. `"etc/nested/file.txt"`).
 * Intermediate directories must already exist in the overlay.
 */
void krun_fs_overlay_add_file(KrunFsOverlay handle, KrunStr path, KrunBytes data, uint32_t mode, bool one_shot);
typedef void (*krun_fs_overlay_add_file_fn)(KrunFsOverlay handle, KrunStr path, KrunBytes data, uint32_t mode, bool one_shot);
void krun_fs_overlay_destroy(KrunFsOverlay handle);
typedef void (*krun_fs_overlay_destroy_fn)(KrunFsOverlay handle);

/* Payload ----------------------------------------------------------- */

KrunPayload krun_payload_load_krunfw(KrunError* err_out);
typedef KrunPayload (*krun_payload_load_krunfw_fn)(KrunError* err_out);
KrunPayload krun_payload_load_krunfw_tee(KrunStr tee_config_path, KrunError* err_out);
typedef KrunPayload (*krun_payload_load_krunfw_tee_fn)(KrunStr tee_config_path, KrunError* err_out);
KrunPayload krun_payload_load_external(KrunStr path, uint32_t format, KrunStr cmdline, KrunError* err_out);
typedef KrunPayload (*krun_payload_load_external_fn)(KrunStr path, uint32_t format, KrunStr cmdline, KrunError* err_out);
KrunPayload krun_payload_load_firmware(KrunStr path, KrunStr cmdline, KrunError* err_out);
typedef KrunPayload (*krun_payload_load_firmware_fn)(KrunStr path, KrunStr cmdline, KrunError* err_out);
KrunStr krun_payload_cmdline(KrunPayload handle);
typedef KrunStr (*krun_payload_cmdline_fn)(KrunPayload handle);
void krun_payload_append_cmdline(KrunPayload handle, KrunStr extra);
typedef void (*krun_payload_append_cmdline_fn)(KrunPayload handle, KrunStr extra);
void krun_payload_destroy(KrunPayload handle);
typedef void (*krun_payload_destroy_fn)(KrunPayload handle);

/* VmmBuilder -------------------------------------------------------- */

KrunVmmBuilder krun_vmm_builder_new();
typedef KrunVmmBuilder (*krun_vmm_builder_new_fn)();
KrunResult krun_vmm_builder_vcpus(KrunVmmBuilder* handle, uint8_t count, KrunError* err_out);
typedef KrunResult (*krun_vmm_builder_vcpus_fn)(KrunVmmBuilder* handle, uint8_t count, KrunError* err_out);
KrunResult krun_vmm_builder_ram_mib(KrunVmmBuilder* handle, uint32_t mib, KrunError* err_out);
typedef KrunResult (*krun_vmm_builder_ram_mib_fn)(KrunVmmBuilder* handle, uint32_t mib, KrunError* err_out);
void krun_vmm_builder_payload(KrunVmmBuilder* handle, KrunPayload payload);
typedef void (*krun_vmm_builder_payload_fn)(KrunVmmBuilder* handle, KrunPayload payload);
void krun_vmm_builder_devices(KrunVmmBuilder* handle, KrunMmioDeviceManager devices);
typedef void (*krun_vmm_builder_devices_fn)(KrunVmmBuilder* handle, KrunMmioDeviceManager devices);
void krun_vmm_builder_set_kernel_console(KrunVmmBuilder* handle, KrunStr console);
typedef void (*krun_vmm_builder_set_kernel_console_fn)(KrunVmmBuilder* handle, KrunStr console);
/**
 * Add a legacy serial console device with the given input and output file descriptors.
 *
 * Can be called multiple times to add multiple serial consoles (ttyS0, ttyS1, …).
 * This is required for FreeBSD guests which use the legacy serial console instead
 * of the virtio console.
 */
void krun_vmm_builder_add_serial_console(KrunVmmBuilder* handle, int input_fd, int output_fd);
typedef void (*krun_vmm_builder_add_serial_console_fn)(KrunVmmBuilder* handle, int input_fd, int output_fd);
void krun_vmm_builder_nested_virt(KrunVmmBuilder* handle, bool enabled);
typedef void (*krun_vmm_builder_nested_virt_fn)(KrunVmmBuilder* handle, bool enabled);
KrunResult krun_vmm_builder_split_irqchip(KrunVmmBuilder* handle, bool enabled, KrunError* err_out);
typedef KrunResult (*krun_vmm_builder_split_irqchip_fn)(KrunVmmBuilder* handle, bool enabled, KrunError* err_out);
void krun_vmm_builder_add_smbios_oem_string(KrunVmmBuilder* handle, KrunStr s);
typedef void (*krun_vmm_builder_add_smbios_oem_string_fn)(KrunVmmBuilder* handle, KrunStr s);
KrunVmm krun_vmm_builder_build(KrunVmmBuilder* handle, KrunError* err_out);
typedef KrunVmm (*krun_vmm_builder_build_fn)(KrunVmmBuilder* handle, KrunError* err_out);
void krun_vmm_builder_destroy(KrunVmmBuilder handle);
typedef void (*krun_vmm_builder_destroy_fn)(KrunVmmBuilder handle);

/* Vmm --------------------------------------------------------------- */

/**
 * Obtain a thread-safe handle to the inner VMM.
 *
 * Must be called before [`run`](Self::run) which consumes `self`.
 * The handle can be moved to another thread for pause/resume.
 */
KrunVmmHandle krun_vmm_handle(KrunVmm handle, KrunError* err_out);
typedef KrunVmmHandle (*krun_vmm_handle_fn)(KrunVmm handle, KrunError* err_out);
void krun_vmm_run(KrunVmm handle);
typedef void (*krun_vmm_run_fn)(KrunVmm handle);
void krun_vmm_destroy(KrunVmm handle);
typedef void (*krun_vmm_destroy_fn)(KrunVmm handle);

/* VmmHandle --------------------------------------------------------- */

KrunResult krun_vmm_handle_pause(KrunVmmHandle handle, KrunError* err_out);
typedef KrunResult (*krun_vmm_handle_pause_fn)(KrunVmmHandle handle, KrunError* err_out);
KrunResult krun_vmm_handle_resume(KrunVmmHandle handle, KrunError* err_out);
typedef KrunResult (*krun_vmm_handle_resume_fn)(KrunVmmHandle handle, KrunError* err_out);
void krun_vmm_handle_destroy(KrunVmmHandle handle);
typedef void (*krun_vmm_handle_destroy_fn)(KrunVmmHandle handle);

/* BalloonDevice ----------------------------------------------------- */

KrunBalloonDevice krun_balloon_device_new(KrunError* err_out);
typedef KrunBalloonDevice (*krun_balloon_device_new_fn)(KrunError* err_out);
void krun_balloon_device_destroy(KrunBalloonDevice handle);
typedef void (*krun_balloon_device_destroy_fn)(KrunBalloonDevice handle);

/* RngDevice --------------------------------------------------------- */

KrunRngDevice krun_rng_device_new(KrunError* err_out);
typedef KrunRngDevice (*krun_rng_device_new_fn)(KrunError* err_out);
void krun_rng_device_destroy(KrunRngDevice handle);
typedef void (*krun_rng_device_destroy_fn)(KrunRngDevice handle);

/* VsockDevice ------------------------------------------------------- */

/**
 * Create a new vsock device.
 *
 * `tsi_features` is a bitmask of TSI flags (0 to disable).
 */
KrunVsockDevice krun_vsock_device_new(uint64_t cid, uint32_t tsi_features, KrunError* err_out);
typedef KrunVsockDevice (*krun_vsock_device_new_fn)(uint64_t cid, uint32_t tsi_features, KrunError* err_out);
/** Add a host port forwarding: `"guest_port:host_port"`. */
KrunResult krun_vsock_device_add_port_forward(KrunVsockDevice handle, KrunStr mapping, KrunError* err_out);
typedef KrunResult (*krun_vsock_device_add_port_forward_fn)(KrunVsockDevice handle, KrunStr mapping, KrunError* err_out);
/** Add a Unix socket port mapping. */
void krun_vsock_device_add_unix_port(KrunVsockDevice handle, uint32_t port, KrunStr path, bool listen);
typedef void (*krun_vsock_device_add_unix_port_fn)(KrunVsockDevice handle, uint32_t port, KrunStr path, bool listen);
void krun_vsock_device_destroy(KrunVsockDevice handle);
typedef void (*krun_vsock_device_destroy_fn)(KrunVsockDevice handle);

/* KrunPushStrVtable ------------------------------------------------- */

#define KRUN_PUSH_STR_TYPE_TAG 16777228

typedef struct {
    void (*drop)(void* self_data);
    bool (*push)(void* self_data, KrunStr s);
} KrunPushStrVtable;

/* PushStr (dispatch) ------------------------------------------------ */

bool krun_push_str_push(KrunPushStr handle, KrunStr s);
typedef bool (*krun_push_str_push_fn)(KrunPushStr handle, KrunStr s);
void krun_push_str_destroy(KrunPushStr handle);
typedef void (*krun_push_str_destroy_fn)(KrunPushStr handle);

/* KrunErrorVtable --------------------------------------------------- */

#define KRUN_ERROR_TYPE_TAG 16777229

typedef struct {
    void (*drop)(void* self_data);
    uint32_t (*code)(void* self_data);
    void (*message)(void* self_data, KrunPushStr writer);
    uint64_t (*result)(void* self_data);
} KrunErrorVtable;

/* Error (dispatch) -------------------------------------------------- */

uint32_t krun_error_code(KrunError handle);
typedef uint32_t (*krun_error_code_fn)(KrunError handle);
void krun_error_message(KrunError handle, KrunPushStr writer);
typedef void (*krun_error_message_fn)(KrunError handle, KrunPushStr writer);
uint64_t krun_error_result(KrunError handle);
typedef uint64_t (*krun_error_result_fn)(KrunError handle);
void krun_error_destroy(KrunError handle);
typedef void (*krun_error_destroy_fn)(KrunError handle);
uint32_t krun_error_code(KrunError handle);
typedef uint32_t (*krun_error_code_fn)(KrunError handle);
void krun_error_message(KrunError handle, KrunPushStr writer);
typedef void (*krun_error_message_fn)(KrunError handle, KrunPushStr writer);

/* Free functions ---------------------------------------------------- */

KrunResult krun_init_log(int target, uint32_t level, uint32_t style, uint32_t options, KrunError* err_out);
typedef KrunResult (*krun_init_log_fn)(int target, uint32_t level, uint32_t style, uint32_t options, KrunError* err_out);
KrunStr krun_result_name(KrunResult r);
typedef KrunStr (*krun_result_name_fn)(KrunResult r);
const char* krun_result_name_cstr(KrunResult r);
typedef const char* (*krun_result_name_cstr_fn)(KrunResult r);

#endif /* LIBKRUN_H */
