/* @generated by: make gen-libkrun-bindings — do not edit manually. */
#ifndef LIBKRUN_H
#define LIBKRUN_H

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>

typedef void* KrunError;
typedef void* KrunMmioDeviceManager;
typedef void* KrunFsDevice;
typedef void* KrunConsoleDevice;
typedef void* KrunConsoleBuilder;
typedef void* KrunFsOverlay;
typedef void* KrunPayload;
typedef void* KrunVmmBuilder;
typedef void* KrunVmm;
typedef void* KrunVmmHandle;
typedef void* KrunBalloonDevice;
typedef void* KrunRngDevice;
typedef void* KrunVsockDevice;
typedef void* KrunBlockDevice;
typedef void* KrunNetDevice;
typedef void* KrunDisplayInfoBuilder;
typedef void* KrunDisplayBackend;
typedef void* KrunGpuDevice;
typedef void* KrunInputDevice;
typedef void* KrunAttachDevice; /* KrunFsDevice | KrunConsoleDevice | KrunBlockDevice | KrunNetDevice | KrunGpuDevice | KrunInputDevice | KrunBalloonDevice | KrunRngDevice | KrunVsockDevice */
typedef void* KrunError; /* KrunError | KrunVtableError */
typedef void* KrunPushStr; /* KrunVtablePushStr */

#ifndef KRUN_PRIMITIVES_DEFINED
#define KRUN_PRIMITIVES_DEFINED

typedef void* KrunObject; /* KrunError | KrunMmioDeviceManager | KrunFsDevice | KrunConsoleDevice | KrunConsoleBuilder | KrunFsOverlay | KrunPayload | KrunVmmBuilder | KrunVmm | KrunVmmHandle | KrunBalloonDevice | KrunRngDevice | KrunVsockDevice | KrunBlockDevice | KrunNetDevice | KrunDisplayInfoBuilder | KrunDisplayBackend | KrunGpuDevice | KrunInputDevice */

typedef uint64_t KrunResult;
#define KRUN_RESULT_SUCCESS 0

/* Caller must ensure data is valid UTF-8 */
typedef struct {
    const char* data;
    size_t len;
} KrunStr;

typedef struct {
    const uint8_t* data;
    size_t len;
} KrunBytes;

#define KRUN_STR(s) ((KrunStr){ .data = (s), .len = (s) ? strlen(s) : 0 })
#if defined(__GNUC__)
#define KRUN_BYTES(arr) ({ \
    _Static_assert( \
        !__builtin_types_compatible_p(typeof(arr), typeof(&(arr)[0])), \
        "KRUN_BYTES() requires an array, not a pointer"); \
    ((KrunBytes){ .data = (const uint8_t*)(arr), .len = sizeof(arr) }); \
})
#else
#define KRUN_BYTES(arr) \
    ((KrunBytes){ .data = (const uint8_t*)(arr), .len = sizeof(arr) })
#endif

/**
 * Stack-allocated temporary handle for passing vtable-based objects.
 * Only valid for the duration of the call — the callee borrows, not owns.
 */
typedef struct {
    uint32_t type_tag;
    uint32_t metadata;
    const void *vtable_ptr;
    const void *user_data;
    uint16_t vtable_size;
} KrunVtableHandle;

#define KRUN_VTABLE_HANDLE(tag, vtable, self_data) \
    ((KrunVtableHandle){ .type_tag = (tag), .metadata = 0, \
      .vtable_ptr = &(vtable), .user_data = (self_data), \
      .vtable_size = sizeof(vtable) })

/**
 * Opaque 16-byte handle entry in an object array.
 * Do not access fields directly — pass &entry to typed methods.
 * Do NOT pass individual entries to destroy.
 */
typedef struct {
    uint32_t _tag;
    uint32_t _meta;
    const void* _ptr;
} KrunObjectArrayEntry;

/**
 * Contiguous array of borrowed handles.
 * Returned by methods that produce slices of handles.
 * Individual elements must NOT be passed to destroy —
 * call free_object_array() to free the entire array.
 */
typedef struct {
    const KrunObjectArrayEntry* items;
    size_t len;
} KrunObjectArray;

#define KRUN_OBJECT_ARRAY_GET(arr, i) \
    (assert((size_t)(i) < (arr).len), (KrunObject)(void*)&(arr).items[(i)])

#endif /* KRUN_PRIMITIVES_DEFINED */

/* Free an owned string returned by the library */
void krun_str_free(KrunStr s);

/* Free an object array returned by the library */
void krun_free_object_array(KrunObjectArray a);


/* KernelFormat ------------------------------------------------------ */

#define KRUN_KERNEL_FORMAT_ELF 0
#define KRUN_KERNEL_FORMAT_RAW 1

/* LogLevel ---------------------------------------------------------- */

#define KRUN_LOG_LEVEL_OFF 0
#define KRUN_LOG_LEVEL_ERROR 1
#define KRUN_LOG_LEVEL_WARN 2
#define KRUN_LOG_LEVEL_INFO 3
#define KRUN_LOG_LEVEL_DEBUG 4
#define KRUN_LOG_LEVEL_TRACE 5

/* LogStyle ---------------------------------------------------------- */

#define KRUN_LOG_STYLE_AUTO 0
#define KRUN_LOG_STYLE_ALWAYS 1
#define KRUN_LOG_STYLE_NEVER 2

/* LogOptions -------------------------------------------------------- */

#define KRUN_LOG_OPTIONS_NO_ENV 1

/* VirglRendererFlags ------------------------------------------------ */

#define KRUN_VIRGL_RENDERER_FLAGS_USE_EGL 1
#define KRUN_VIRGL_RENDERER_FLAGS_THREAD_SYNC 2
#define KRUN_VIRGL_RENDERER_FLAGS_VENUS 64
#define KRUN_VIRGL_RENDERER_FLAGS_USE_ASYNC_FENCE_CB 256
#define KRUN_VIRGL_RENDERER_FLAGS_RENDER_SERVER 512

/* Error ------------------------------------------------------------- */

#define KRUN_ERROR__INVALID_PARAM ((uint64_t)16777229 << 32 | 1)
#define KRUN_ERROR__DUPLICATE_DEVICE ((uint64_t)16777229 << 32 | 2)
#define KRUN_ERROR__DEVICE_LIMIT_EXCEEDED ((uint64_t)16777229 << 32 | 3)
#define KRUN_ERROR__MISSING_CONFIG ((uint64_t)16777229 << 32 | 4)
#define KRUN_ERROR__CONFLICTING_CONFIG ((uint64_t)16777229 << 32 | 5)
#define KRUN_ERROR__OUT_OF_RANGE ((uint64_t)16777229 << 32 | 6)
#define KRUN_ERROR__FILE_NOT_FOUND ((uint64_t)16777229 << 32 | 7)
#define KRUN_ERROR__PERMISSION_DENIED ((uint64_t)16777229 << 32 | 8)
#define KRUN_ERROR__RESOURCE_ALLOC ((uint64_t)16777229 << 32 | 9)
#define KRUN_ERROR__BAD_FD ((uint64_t)16777229 << 32 | 10)
#define KRUN_ERROR__BACKEND_UNAVAILABLE ((uint64_t)16777229 << 32 | 11)
#define KRUN_ERROR__FEATURE_DISABLED ((uint64_t)16777229 << 32 | 12)
#define KRUN_ERROR__DISK_FORMAT_ERROR ((uint64_t)16777229 << 32 | 13)
#define KRUN_ERROR__ALREADY_STARTED ((uint64_t)16777229 << 32 | 14)
#define KRUN_ERROR__VALIDATION_FAILED ((uint64_t)16777229 << 32 | 15)
#define KRUN_ERROR__HYPERVISOR_ERROR ((uint64_t)16777229 << 32 | 16)
#define KRUN_ERROR__BOOT_ERROR ((uint64_t)16777229 << 32 | 17)
#define KRUN_ERROR__INTERNAL ((uint64_t)16777229 << 32 | 18)

/* MmioDeviceManager ------------------------------------------------- */

/** Create an empty device manager. */
KrunMmioDeviceManager krun_mmio_device_manager_new();
/**
 * Add a device to this manager.
 *
 * Devices are attached in the order they are added. The device must
 * implement [`AttachDevice`] — all built-in device types
 * (`FsDevice`, `ConsoleDevice`, etc.) implement this trait.
 */
void krun_mmio_device_manager_add(KrunMmioDeviceManager handle, KrunAttachDevice device);
void krun_mmio_device_manager_destroy(KrunMmioDeviceManager handle);

/* FsDevice ---------------------------------------------------------- */

/**
 * Create a new virtiofs device sharing a host directory.
 *
 * # Arguments
 *
 * - `tag`: the filesystem tag visible to the guest (e.g. `"/dev/root"`).
 * - `host_path`: the host directory to share.
 */
KrunFsDevice krun_fs_device_new(KrunStr tag, KrunStr host_path, KrunError* err_out);
/** Create a read-only virtiofs device sharing a host directory. */
KrunFsDevice krun_fs_device_new_read_only(KrunStr tag, KrunStr host_path, KrunError* err_out);
/**
 * Create a virtiofs device with no host directory (NullFs).
 *
 * The guest sees an empty filesystem. Use [`FsOverlay`] to build
 * virtual entries and [`set_overlay`](Self::set_overlay) to attach
 * them.
 */
KrunFsDevice krun_fs_device_new_null(KrunStr tag, KrunError* err_out);
/**
 * Set a pre-built [`FsOverlay`] on this device.
 *
 * The overlay entries are resolved (applied to the underlying
 * virtiofs device) during [`attach`](AttachDevice::attach).
 */
void krun_fs_device_set_overlay(KrunFsDevice handle, KrunFsOverlay overlay);
/**
 * Set the size of the DAX (direct access) shared memory window.
 *
 * When set, the guest can memory-map files from the shared filesystem
 * directly into its address space, avoiding data copies. If not set,
 * no DAX window is allocated.
 */
void krun_fs_device_set_dax_window_size(KrunFsDevice handle, uint64_t bytes);
void krun_fs_device_destroy(KrunFsDevice handle);

/* ConsoleDevice ----------------------------------------------------- */

/** Create a new console builder. */
KrunConsoleBuilder krun_console_device_builder();
void krun_console_device_destroy(KrunConsoleDevice handle);

/* ConsoleBuilder ---------------------------------------------------- */

/**
 * Add a TTY-backed port to the console.
 *
 * If the fd refers to a real terminal, raw mode will be enabled on it
 * when the VM starts, and restored on shutdown.
 *
 * # Arguments
 *
 * - `name`: the port name visible to the guest (e.g. `"tty0"`).
 * - `tty_fd`: borrowed fd for the host TTY; duplicated internally, caller retains ownership.
 *
 * # Returns
 *
 * The zero-based port index.
 */
KrunResult krun_console_builder_add_tty_port(KrunConsoleBuilder handle, KrunStr name, int tty_fd, uint32_t* result, KrunError* err_out);
/**
 * Add a port with separate input and output fds (no terminal properties).
 * Pass `None` to disable that direction.
 */
KrunResult krun_console_builder_add_inout_port(KrunConsoleBuilder handle, KrunStr name, int input_fd, int output_fd, uint32_t* result, KrunError* err_out);
/** Build the console device. At least one port must have been added. */
KrunConsoleDevice krun_console_builder_build(KrunConsoleBuilder handle, KrunError* err_out);
/**
 * Set up the default console: port 0 (hvc0) plus named redirect ports.
 *
 * Replicates the v1 `krun_add_virtio_console_default` behaviour:
 *
 * - If any fd is a terminal, port 0 becomes a full TTY console
 *   (raw mode enabled), and that fd is NOT added as a redirect port.
 * - Otherwise, port 0 gets log output and named redirect ports
 *   (`krun-stdin`, `krun-stdout`, `krun-stderr`) are added.
 *
 * Pass `None` to skip a stream.
 */
KrunResult krun_console_builder_add_default_console(KrunConsoleBuilder handle, int stdin, int stdout, int stderr, KrunError* err_out);
void krun_console_builder_destroy(KrunConsoleBuilder handle);

/* FsOverlay --------------------------------------------------------- */

/** Create a new empty overlay. */
KrunFsOverlay krun_fs_overlay_new();
/**
 * Add a virtual directory entry.
 *
 * `path` may contain `/` separators for nested entries (e.g. `"etc/nested"`).
 * Intermediate directories must already exist in the overlay.
 */
void krun_fs_overlay_add_dir(KrunFsOverlay handle, KrunStr path, uint32_t mode);
/**
 * Add a virtual file entry.
 *
 * `path` may contain `/` separators for nested entries (e.g. `"etc/nested/file.txt"`).
 * Intermediate directories must already exist in the overlay.
 */
void krun_fs_overlay_add_file(KrunFsOverlay handle, KrunStr path, KrunBytes data, uint32_t mode, bool one_shot);
void krun_fs_overlay_destroy(KrunFsOverlay handle);

/* Payload ----------------------------------------------------------- */

KrunPayload krun_payload_load_krunfw(KrunError* err_out);
KrunPayload krun_payload_load_krunfw_tee(KrunStr tee_config_path, KrunError* err_out);
KrunPayload krun_payload_load_external(KrunStr path, uint32_t format, KrunStr cmdline, KrunError* err_out);
KrunPayload krun_payload_load_firmware(KrunStr path, KrunStr cmdline, KrunError* err_out);
KrunStr krun_payload_cmdline(KrunPayload handle);
void krun_payload_append_cmdline(KrunPayload handle, KrunStr extra);
void krun_payload_destroy(KrunPayload handle);

/* VmmBuilder -------------------------------------------------------- */

KrunVmmBuilder krun_vmm_builder_new();
KrunResult krun_vmm_builder_vcpus(KrunVmmBuilder* handle, uint8_t count, KrunError* err_out);
KrunResult krun_vmm_builder_ram_mib(KrunVmmBuilder* handle, uint32_t mib, KrunError* err_out);
void krun_vmm_builder_payload(KrunVmmBuilder* handle, KrunPayload payload);
void krun_vmm_builder_devices(KrunVmmBuilder* handle, KrunMmioDeviceManager devices);
void krun_vmm_builder_set_kernel_console(KrunVmmBuilder* handle, KrunStr console);
/**
 * Add a legacy serial console device with the given input and output file descriptors.
 *
 * Can be called multiple times to add multiple serial consoles (ttyS0, ttyS1, …).
 * This is required for FreeBSD guests which use the legacy serial console instead
 * of the virtio console.
 */
void krun_vmm_builder_add_serial_console(KrunVmmBuilder* handle, int input_fd, int output_fd);
void krun_vmm_builder_nested_virt(KrunVmmBuilder* handle, bool enabled);
KrunResult krun_vmm_builder_split_irqchip(KrunVmmBuilder* handle, bool enabled, KrunError* err_out);
void krun_vmm_builder_add_smbios_oem_string(KrunVmmBuilder* handle, KrunStr s);
KrunVmm krun_vmm_builder_build(KrunVmmBuilder* handle, KrunError* err_out);
void krun_vmm_builder_destroy(KrunVmmBuilder handle);

/* Vmm --------------------------------------------------------------- */

/**
 * Obtain a thread-safe handle to the inner VMM.
 *
 * Must be called before [`run`](Self::run) which consumes `self`.
 * The handle can be moved to another thread for pause/resume.
 */
KrunVmmHandle krun_vmm_handle(KrunVmm handle, KrunError* err_out);
void krun_vmm_run(KrunVmm handle);
void krun_vmm_destroy(KrunVmm handle);

/* VmmHandle --------------------------------------------------------- */

KrunResult krun_vmm_handle_pause(KrunVmmHandle handle, KrunError* err_out);
KrunResult krun_vmm_handle_resume(KrunVmmHandle handle, KrunError* err_out);
void krun_vmm_handle_destroy(KrunVmmHandle handle);

/* BalloonDevice ----------------------------------------------------- */

KrunBalloonDevice krun_balloon_device_new(KrunError* err_out);
void krun_balloon_device_destroy(KrunBalloonDevice handle);

/* RngDevice --------------------------------------------------------- */

KrunRngDevice krun_rng_device_new(KrunError* err_out);
void krun_rng_device_destroy(KrunRngDevice handle);

/* VsockDevice ------------------------------------------------------- */

/**
 * Create a new vsock device.
 *
 * `tsi_features` is a bitmask of TSI flags (0 to disable).
 */
KrunVsockDevice krun_vsock_device_new(uint64_t cid, uint32_t tsi_features, KrunError* err_out);
/** Add a host port forwarding: `"guest_port:host_port"`. */
KrunResult krun_vsock_device_add_port_forward(KrunVsockDevice handle, KrunStr mapping, KrunError* err_out);
/** Add a Unix socket port mapping. */
void krun_vsock_device_add_unix_port(KrunVsockDevice handle, uint32_t port, KrunStr path, bool listen);
void krun_vsock_device_destroy(KrunVsockDevice handle);

/* BlockDevice ------------------------------------------------------- */

KrunBlockDevice krun_block_device_new(KrunStr id, KrunStr disk_image_path, bool is_read_only, KrunError* err_out);
void krun_block_device_destroy(KrunBlockDevice handle);

/* NetDevice --------------------------------------------------------- */

/** Create a net device backed by a Unix datagram socket path. */
KrunNetDevice krun_net_device_new_unixgram_path(KrunStr id, KrunStr path, KrunBytes mac, uint32_t features, bool vfkit_magic, KrunError* err_out);
/**
 * Create a net device backed by a Unix datagram socket fd.
 *
 * Takes ownership of `fd`; the caller must not close it after this call.
 */
KrunNetDevice krun_net_device_new_unixgram_fd(KrunStr id, int fd, KrunBytes mac, uint32_t features, KrunError* err_out);
/** Create a net device backed by a Unix stream socket path. */
KrunNetDevice krun_net_device_new_unixstream_path(KrunStr id, KrunStr path, KrunBytes mac, uint32_t features, KrunError* err_out);
/**
 * Create a net device backed by a Unix stream socket fd.
 *
 * Takes ownership of `fd`; the caller must not close it after this call.
 */
KrunNetDevice krun_net_device_new_unixstream_fd(KrunStr id, int fd, KrunBytes mac, uint32_t features, KrunError* err_out);
KrunNetDevice krun_net_device_new_tap(KrunStr id, KrunStr tap_name, KrunBytes mac, uint32_t features, KrunError* err_out);
void krun_net_device_destroy(KrunNetDevice handle);

/* DisplayInfoBuilder ------------------------------------------------ */

KrunDisplayInfoBuilder krun_display_info_builder_new(uint32_t width, uint32_t height);
void krun_display_info_builder_edid(KrunDisplayInfoBuilder* handle, KrunBytes edid);
void krun_display_info_builder_dpi(KrunDisplayInfoBuilder* handle, uint32_t dpi);
void krun_display_info_builder_physical_size(KrunDisplayInfoBuilder* handle, uint16_t width_mm, uint16_t height_mm);
void krun_display_info_builder_refresh_rate(KrunDisplayInfoBuilder* handle, uint32_t rate);
void krun_display_info_builder_destroy(KrunDisplayInfoBuilder handle);

/* DisplayBackend ---------------------------------------------------- */

/**
 * Create from the opaque pre-ffier `krun_display_backend` vtable pointer.
 *
 * # Safety
 *
 * `vtable` must point to a valid `krun_display_backend` struct of at least
 * `vtable_size` bytes. The struct is copied — the caller retains ownership
 * of the original.
 */
KrunDisplayBackend krun_display_backend_new(const void* vtable, size_t vtable_size, KrunError* err_out);
void krun_display_backend_add_display(KrunDisplayBackend handle, KrunDisplayInfoBuilder display);
void krun_display_backend_destroy(KrunDisplayBackend handle);

/* GpuDevice --------------------------------------------------------- */

KrunGpuDevice krun_gpu_device_new(uint32_t virgl_flags, KrunDisplayBackend backend);
void krun_gpu_device_shm_size(KrunGpuDevice* handle, size_t size);
void krun_gpu_device_destroy(KrunGpuDevice handle);

/* InputDevice ------------------------------------------------------- */

/**
 * Create from opaque config/events backend vtables.
 *
 * # Safety
 *
 * `config_backend` must point to a valid `InputConfigBackend` struct of at
 * least `config_backend_size` bytes, and `event_provider_backend` must
 * point to a valid `InputEventProviderBackend` struct of at least
 * `event_provider_backend_size` bytes. Both structs are copied — the
 * caller retains ownership of the originals.
 */
KrunInputDevice krun_input_device_new(const void* config_backend, size_t config_backend_size, const void* event_provider_backend, size_t event_provider_backend_size, KrunError* err_out);
/**
 * Create a passthrough input device from an evdev fd.
 *
 * The fd must refer to a Linux `/dev/input/eventN` device. It is
 * duplicated internally; the caller retains ownership.
 * Create a passthrough input device from an evdev fd.
 *
 * The fd must refer to a Linux `/dev/input/eventN` device. It is
 * duplicated internally; the caller retains ownership.
 */
KrunInputDevice krun_input_device_new_from_fd(int input_fd, KrunError* err_out);
void krun_input_device_destroy(KrunInputDevice handle);

/* KrunPushStrVtable ------------------------------------------------- */

#define KRUN_PUSH_STR_TYPE_TAG 16777228

typedef struct {
    void (*drop)(void* self_data);
    bool (*push)(void* self_data, KrunStr s);
} KrunPushStrVtable;

/* PushStr (dispatch) ------------------------------------------------ */

bool krun_push_str_push(KrunPushStr handle, KrunStr s);
void krun_push_str_destroy(KrunPushStr handle);

/* KrunErrorVtable --------------------------------------------------- */

#define KRUN_ERROR_TYPE_TAG 16777229

typedef struct {
    void (*drop)(void* self_data);
    uint32_t (*code)(void* self_data);
    void (*message)(void* self_data, KrunPushStr writer);
    uint64_t (*result)(void* self_data);
} KrunErrorVtable;

/* Error (dispatch) -------------------------------------------------- */

uint32_t krun_error_code(KrunError handle);
void krun_error_message(KrunError handle, KrunPushStr writer);
uint64_t krun_error_result(KrunError handle);
void krun_error_destroy(KrunError handle);
uint32_t krun_error_code(KrunError handle);
void krun_error_message(KrunError handle, KrunPushStr writer);

/* Free functions ---------------------------------------------------- */

KrunResult krun_init_log(int target, uint32_t level, uint32_t style, uint32_t options, KrunError* err_out);
KrunStr krun_result_name(KrunResult r);
const char* krun_result_name_cstr(KrunResult r);

#endif /* LIBKRUN_H */
